version: "3.2"
services:
  redis:
    restart: always
    image: redis:5
    ports:
      - "6379:6379"
    networks:
      - db-net

  db:
    restart: always
    image: mariadb:5.5
    environment:
      - MYSQL_HOST=localhost
      - MYSQL_PORT=3306
      - MYSQL_ROOT_HOST=%
      - MYSQL_DATABASE=database
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3302:3306"
    networks:
      - db-net

  backend:
    restart: always
    container_name: backend
    command : bash -c "python check_db.py --service-name db --ip db --port 3306 &&
                      python manage.py migrate &&
                      python manage.py runserver 0.0.0.0:8000"
    env_file:
      - ./backend/backend/settings.ini
    build:
      context: ./backend/
      dockerfile: dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    networks:
      - db-net

  frontend:
    restart: always
    command : npm start
    container_name: frontend
    build:
      context: ./frontend/
      dockerfile: dockerfile
    ports:
      - "3000:3000"
    stdin_open: true
    depends_on:
      - backend
    networks:
      - db-net

networks:
  db-net:
    driver: bridge