FROM python:3
ENV PYTHONUNBUFFERED 1
WORKDIR /app/api

#Instalando dependencias
RUN pip install --upgrade pip
COPY requirements.txt ./
RUN pip install -r requirements.txt

#Copiar proyecto
COPY . ./

EXPOSE 8000

CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]